using UnityEngine;
using UnityEditor;
using System.Collections.Generic;
using System.Linq;
using nadena.dev.modular_avatar.core;
using nadena.dev.modular_avatar.core.vertex_filters;
using VRC.SDK3.Avatars.ScriptableObjects;

namespace vrc_yue.MeshUVCutTools.MeshModifyTool
{
    [CustomEditor(typeof(MUCTMeshRemovalData))]
    [CanEditMultipleObjects]
    public class MeshRemovalDataEditor : Editor
    {
        // 日英対応用のローカライズメソッド
        private string L(string ja, string en)
        {
            return Application.systemLanguage == SystemLanguage.Japanese ? ja : en;
        }
        
        // Publicメソッド（MeshModifyToolから呼び出すため）
        public void SetupModularAvatarComponentsPublic(MUCTMeshRemovalData targetData)
        {
            SetupModularAvatarComponents(targetData);
        }
        
        public void RemoveModularAvatarComponentsPublic(MUCTMeshRemovalData targetData)
        {
            RemoveModularAvatarComponents(targetData);
        }
        
        public override void OnInspectorGUI()
        {
            serializedObject.Update();
            
            // Enableチェックボックスを描画
            EditorGUI.BeginChangeCheck();
            EditorGUILayout.PropertyField(serializedObject.FindProperty("m_Enabled"));
            if (EditorGUI.EndChangeCheck())
            {
                serializedObject.ApplyModifiedProperties();
                // オブジェクトを更新済みとマーク
                foreach (var obj in targets)
                {
                    EditorUtility.SetDirty(obj);
                }
                // プレビューを即座に更新
                SceneView.RepaintAll();
                // NDMFプレビューの更新をトリガー
                UnityEditor.EditorApplication.QueuePlayerLoopUpdate();
            }
            
            var removalData = (MUCTMeshRemovalData)target;
            
            EditorGUILayout.Space();
            
            // 自動生成されたコンポーネントであることを示す説明
            EditorGUILayout.HelpBox(
                L("このコンポーネントは「ちゅんちゅんメッシュカッター」によって自動生成されました。\nNDMFビルド時に指定された頂点が削除されます。",
                  "This component was automatically generated by 'ChunChun Mesh Cutter'.\nSpecified vertices will be removed during NDMF build."),
                MessageType.Info);
            
            EditorGUILayout.Space();
            
            // Display removal info
            EditorGUILayout.LabelField(L("メッシュ削除情報", "Mesh Removal Info"), EditorStyles.boldLabel);
            
            if (removalData.removalInfos.Count == 0)
            {
                EditorGUILayout.HelpBox(L("メッシュ削除データが設定されていません。", "No mesh removal data configured."), MessageType.Info);
            }
            else
            {
                foreach (var info in removalData.removalInfos)
                {
                    if (info.targetRenderer == null) continue;
                    
                    EditorGUILayout.BeginVertical(GUI.skin.box);
                    EditorGUILayout.LabelField(L($"レンダラー: {info.targetRenderer.name}", $"Renderer: {info.targetRenderer.name}"));
                    EditorGUILayout.LabelField(L($"削除する頂点数: {info.verticesToRemove.Count}", $"Vertices to Remove: {info.verticesToRemove.Count}"));
                    EditorGUILayout.EndVertical();
                }
            }
            
            EditorGUILayout.Space();
            
            // ModularAvatar統合オプション
            var targetData = target as MUCTMeshRemovalData;
            if (targetData != null && targetData.removalInfos.Count > 0 && 
                targetData.removalInfos.Any(info => info.verticesToRemove.Count > 0))
            {
                EditorGUILayout.BeginVertical("HelpBox");
                EditorGUILayout.LabelField(L("削除方法", "Removal Method"), EditorStyles.boldLabel);
                
                
                if (!targetData.UseModularAvatar)
                {
                    // 通常モード
                    EditorGUILayout.LabelField(L("現在: 通常削除モード", "Current: Normal Delete Mode"), EditorStyles.miniLabel);
                    EditorGUILayout.HelpBox(
                        L("ビルド時にメッシュから頂点を完全に削除します。削除後は復元できません。",
                          "Vertices will be completely removed from the mesh during build. Cannot be restored after deletion."), 
                        MessageType.None);
                    
                    if (GUILayout.Button(L("ModularAvatarでアニメーション制御可能にする", "Enable Animation Control with ModularAvatar")))
                    {
                        SetupModularAvatarComponents(targetData);
                    }
                }
                else
                {
                    // ModularAvatarモード
                    EditorGUILayout.LabelField(L("現在: ModularAvatar連携モード", "Current: ModularAvatar Integration Mode"), EditorStyles.miniLabel);
                    EditorGUILayout.HelpBox(
                        L("ModularAvatarコンポーネントが設定されています。\n" +
                          "• ビルド時に削除用BlendShapeが自動生成されます\n" +
                          "• VRChatでアニメーション制御可能になります",
                          "ModularAvatar components are configured.\n" +
                          "• BlendShape for deletion will be automatically generated during build\n" +
                          "• Can be controlled via animation in VRChat"), 
                        MessageType.Info);
                    
                    if (GUILayout.Button(L("通常の削除に戻す", "Return to Normal Deletion")))
                    {
                        RemoveModularAvatarComponents(targetData);
                    }
                    
                    EditorGUILayout.HelpBox(
                        L("注意: 「通常の削除に戻す」を押すと、コンソールにMissingReferenceExceptionが表示される場合がありますが、これは表示上の問題で機能には影響ありません。",
                          "Note: When clicking 'Return to Normal Deletion', a MissingReferenceException may appear in the console. This is only a display issue and does not affect functionality."), 
                        MessageType.None);
                }
                
                EditorGUILayout.EndVertical();
            }
            
            EditorGUILayout.Space();
            
            // NDMFプレビュー情報
            if (targetData != null && !targetData.UseModularAvatar)
            {
                EditorGUILayout.HelpBox(
                    L("NDMFプレビューが有効な場合、シーンビューに自動的にプレビューが表示されます。",
                      "Preview is automatically shown in Scene view when NDMF Preview is enabled."), 
                    MessageType.Info);
            }
            
            // 最後に変更を適用
            serializedObject.ApplyModifiedProperties();
        }
        
        private void SetupModularAvatarComponents(MUCTMeshRemovalData targetData)
        {
            Undo.RecordObject(targetData, "Setup ModularAvatar Components");
            
            // UseModularAvatarフラグを設定
            targetData.UseModularAvatar = true;
            
            var renderer = targetData.GetComponent<SkinnedMeshRenderer>();
            if (renderer == null)
            {
                EditorUtility.DisplayDialog(
                    L("エラー", "Error"), 
                    L("SkinnedMeshRendererが見つかりません。", "SkinnedMeshRenderer not found."), 
                    "OK");
                return;
            }
            
            // 既存の関連コンポーネントをチェックして削除
            RemoveExistingMAComponents(targetData);
            
            // トグル用の子GameObjectを作成または取得
            GameObject toggleObject = null;
            for (int i = 0; i < targetData.transform.childCount; i++)
            {
                var child = targetData.transform.GetChild(i);
                if (child.name == "MUCT Delete Toggle")
                {
                    toggleObject = child.gameObject;
                    break;
                }
            }
            
            if (toggleObject == null)
            {
                toggleObject = new GameObject("MUCT Delete Toggle");
                toggleObject.transform.SetParent(targetData.transform, false);
                Undo.RegisterCreatedObjectUndo(toggleObject, "Create MUCT Toggle");
            }
            
            // ModularAvatar MeshCutterを子に追加（1つのGameObjectに1つだけ）
            var meshCutter = toggleObject.GetComponent<ModularAvatarMeshCutter>();
            if (meshCutter == null)
            {
                // 他のMUCTMeshRemovalDataがMA使用中かチェック
                var otherRemovalDatas = targetData.gameObject.GetComponents<MUCTMeshRemovalData>();
                bool hasOtherMAEnabled = false;
                foreach (var other in otherRemovalDatas)
                {
                    if (other != targetData && other.UseModularAvatar)
                    {
                        hasOtherMAEnabled = true;
                        break;
                    }
                }
                
                // 他のMAが有効でない場合のみMeshCutterを追加
                if (!hasOtherMAEnabled)
                {
                    meshCutter = Undo.AddComponent<ModularAvatarMeshCutter>(toggleObject);
                    meshCutter.Object = new AvatarObjectReference();
                    meshCutter.Object.Set(renderer.gameObject);
                    // "vertices selected by any filter"に相当するVertexUnionを設定
                    meshCutter.MultiMode = MeshCutterMultiMode.VertexUnion;
                }
            }
            
            // 一意な識別子を生成（このMUCTMeshRemovalData用）
            var uniqueId = GenerateUniqueIdentifier(targetData);
            
            // VertexFilterByShapeComponentを子に追加（このMUCTMeshRemovalData専用）
            var shapeFilter = Undo.AddComponent<VertexFilterByShapeComponent>(toggleObject);
            // 一意なBlendShape名を生成
            var shapeName = GenerateUniqueShapeName(targetData, renderer);
            shapeFilter.Shapes = new List<string> { shapeName };
            shapeFilter.Threshold = 0.001f;
            // InstanceIDを記録
            targetData.AssociatedShapeFilterInstanceId = shapeFilter.GetInstanceID();
            
            // MenuItemを子に追加（GameObject全体で1つだけ）
            var existingMenuItem = toggleObject.GetComponent<ModularAvatarMenuItem>();
            if (existingMenuItem == null)
            {
                // MenuItemを追加
                existingMenuItem = Undo.AddComponent<ModularAvatarMenuItem>(toggleObject);
                var paramName = "MUCT_Delete_Mesh";
                existingMenuItem.Control = new VRC.SDK3.Avatars.ScriptableObjects.VRCExpressionsMenu.Control
                {
                    name = L($"Delete {renderer.name}", $"Delete {renderer.name}"),
                    type = VRC.SDK3.Avatars.ScriptableObjects.VRCExpressionsMenu.Control.ControlType.Toggle,
                    parameter = new VRC.SDK3.Avatars.ScriptableObjects.VRCExpressionsMenu.Control.Parameter
                    {
                        name = paramName
                    },
                    value = 1
                };
                // ModularAvatarMenuItemのlabelプロパティを設定
                existingMenuItem.label = L($"Delete {renderer.name}", $"Delete {renderer.name}");
            }
            
            // ObjectToggleを子に追加（GameObject全体で1つだけ）
            var existingObjectToggle = toggleObject.GetComponent<ModularAvatarObjectToggle>();
            if (existingObjectToggle == null)
            {
                existingObjectToggle = Undo.AddComponent<ModularAvatarObjectToggle>(toggleObject);
                existingObjectToggle.Objects = new List<ToggledObject>();
            }
            
            // MenuInstallerを子に追加（GameObject全体で1つだけ）
            var existingMenuInstaller = toggleObject.GetComponent<ModularAvatarMenuInstaller>();
            if (existingMenuInstaller == null)
            {
                Undo.AddComponent<ModularAvatarMenuInstaller>(toggleObject);
            }
            
            // 各MUCTMeshRemovalDataは同じMenuItemを参照
            targetData.AssociatedMenuItemInstanceId = existingMenuItem.GetInstanceID();
            
            EditorUtility.SetDirty(targetData);
            EditorUtility.SetDirty(targetData.gameObject);
            EditorUtility.SetDirty(toggleObject);
        }
        
        private void RemoveModularAvatarComponents(MUCTMeshRemovalData targetData)
        {
            Undo.RecordObject(targetData, "Remove ModularAvatar Components");
            
            // UseModularAvatarフラグを解除
            targetData.UseModularAvatar = false;
            
            // 子GameObjectのトグルを探す
            GameObject toggleObject = null;
            for (int i = 0; i < targetData.transform.childCount; i++)
            {
                var child = targetData.transform.GetChild(i);
                if (child.name == "MUCT Delete Toggle")
                {
                    toggleObject = child.gameObject;
                    break;
                }
            }
            
            if (toggleObject != null)
            {
                // ShapeFilterを削除（InstanceIDで特定）
                var allShapeFilters = toggleObject.GetComponents<VertexFilterByShapeComponent>();
                foreach (var shapeFilter in allShapeFilters)
                {
                    if (shapeFilter != null && shapeFilter.GetInstanceID() == targetData.AssociatedShapeFilterInstanceId)
                    {
                        Undo.DestroyObjectImmediate(shapeFilter);
                        break;
                    }
                }
                
                // 他のMUCTMeshRemovalDataがMA使用中でない場合のみトグルオブジェクト全体を削除
                var otherRemovalDatas = targetData.gameObject.GetComponents<MUCTMeshRemovalData>();
                bool hasOtherMAEnabled = false;
                foreach (var other in otherRemovalDatas)
                {
                    if (other != targetData && other.UseModularAvatar)
                    {
                        hasOtherMAEnabled = true;
                        break;
                    }
                }
                
                if (!hasOtherMAEnabled)
                {
                    // トグルオブジェクト全体を削除
                    Undo.DestroyObjectImmediate(toggleObject);
                }
            }
            
            // InstanceIDをクリア
            targetData.AssociatedMenuItemInstanceId = 0;
            targetData.AssociatedShapeFilterInstanceId = 0;
            
            EditorUtility.SetDirty(targetData);
            EditorUtility.SetDirty(targetData.gameObject);
        }
        
        private string GenerateUniqueShapeName(MUCTMeshRemovalData data, SkinnedMeshRenderer renderer)
        {
            // オブジェクト名 + 短いハッシュで自動生成
            var baseName = data.gameObject.name;
            var shortHash = Mathf.Abs(data.GetInstanceID() % 1000).ToString("D3");
            var shapeName = $"MUCT_{baseName}_{shortHash}";
            
            // 一意性チェック（同じメッシュに同じ名前のBlendShapeがないか）
            if (renderer != null && renderer.sharedMesh != null)
            {
                var existingNames = new HashSet<string>();
                var mesh = renderer.sharedMesh;
                
                for (int i = 0; i < mesh.blendShapeCount; i++)
                {
                    existingNames.Add(mesh.GetBlendShapeName(i));
                }
                
                // 他のMUCTMeshRemovalDataもチェック
                var allRemovalData = renderer.GetComponents<MUCTMeshRemovalData>();
                foreach (var otherData in allRemovalData)
                {
                    if (otherData != data && otherData.UseModularAvatar)
                    {
                        var otherFilter = otherData.GetComponent<VertexFilterByShapeComponent>();
                        if (otherFilter != null && otherFilter.Shapes.Count > 0)
                        {
                            existingNames.Add(otherFilter.Shapes[0]);
                        }
                    }
                }
                
                // 一意でない場合は番号を付与
                if (existingNames.Contains(shapeName))
                {
                    for (int i = 1; i < 100; i++)
                    {
                        var numberedName = $"{shapeName}_{i:D2}";
                        if (!existingNames.Contains(numberedName))
                        {
                            return numberedName;
                        }
                    }
                }
            }
            
            return shapeName;
        }
        
        private string GenerateUniqueIdentifier(MUCTMeshRemovalData data)
        {
            // InstanceIDベースで一意な識別子を生成
            return data.GetInstanceID().ToString();
        }
        
        private void RemoveExistingMAComponents(MUCTMeshRemovalData targetData)
        {
            // 既存の関連コンポーネントを削除（InstanceIDで特定）
            if (targetData.AssociatedMenuItemInstanceId != 0)
            {
                var allMenuItems = targetData.gameObject.GetComponents<ModularAvatarMenuItem>();
                foreach (var menuItem in allMenuItems)
                {
                    if (menuItem != null && menuItem.GetInstanceID() == targetData.AssociatedMenuItemInstanceId)
                    {
                        DestroyImmediate(menuItem);
                        break;
                    }
                }
            }
            
            if (targetData.AssociatedShapeFilterInstanceId != 0)
            {
                var allShapeFilters = targetData.gameObject.GetComponents<VertexFilterByShapeComponent>();
                foreach (var shapeFilter in allShapeFilters)
                {
                    if (shapeFilter != null && shapeFilter.GetInstanceID() == targetData.AssociatedShapeFilterInstanceId)
                    {
                        DestroyImmediate(shapeFilter);
                        break;
                    }
                }
            }
            
            // InstanceIDをクリア
            targetData.AssociatedMenuItemInstanceId = 0;
            targetData.AssociatedShapeFilterInstanceId = 0;
        }
    }
}